In [2]:
!pip uninstall torch -y
!pip uninstall torchvision -y
!pip install torch 
!pip install torchvision
import torch 
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms

Found existing installation: torch 1.9.0
Uninstalling torch-1.9.0:
  Successfully uninstalled torch-1.9.0
Found existing installation: torchvision 0.10.0
Uninstalling torchvision-0.10.0:
  Successfully uninstalled torchvision-0.10.0
  Using cached torch-1.9.0-cp37-cp37m-manylinux1_x86_64.whl (831.4 MB)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastai 2.2.7 requires torchvision<0.9,>=0.8, which is not installed.
easyocr 1.3.2 requires torchvision>=0.5, which is not installed.
allennlp 2.5.0 requires torchvision<0.10.0,>=0.8.1, which is not installed.
kornia 0.5.5 requires numpy<=1.19, but you have numpy 1.19.5 which is incompatible.
fastai 2.2.7 requires torch<1.8,>=1.7.0, but you have torch 1.9.0 which is incompatible.
allennlp 2.5.0 requires torch<1.9.0,>=1.6.0, but you have torch 1.9.0 which is incompatible.
  Using cached torchvision-0.10.0-cp37-cp37m-

In [3]:
# ================================================================== #
#                         Table of Contents                          #
# ================================================================== #

# 1. Basic autograd example 1               (Line 25 to 39)
# 2. Basic autograd example 2               (Line 46 to 83)
# 3. Loading data from numpy                (Line 90 to 97)
# 4. Input pipline                          (Line 104 to 129)
# 5. Input pipline for custom dataset       (Line 136 to 156)
# 6. Pretrained model                       (Line 163 to 176)
# 7. Save and load model                    (Line 183 to 189) 


# ================================================================== #
#                     1. Basic autograd example 1                    #
# ================================================================== #

In [4]:
# Create tensors.
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

In [5]:
# Build a computational graph.
y = w * x + b    # y = 2 * x + 3

In [6]:
print(w,x,b,y)

tensor(2., requires_grad=True) tensor(1., requires_grad=True) tensor(3., requires_grad=True) tensor(5., grad_fn=<AddBackward0>)


In [7]:
# Compute gradients.
y.backward()

In [8]:
# Print out the gradients.
print(x.grad)    # x.grad = 2 
print(w.grad)    # w.grad = 1 
print(b.grad)    # b.grad = 1 


tensor(2.)
tensor(1.)
tensor(1.)


In [9]:
# ================================================================== #
#                    2. Basic autograd example 2                     #
# ================================================================== #

# Create tensors of shape (10, 3) and (10, 2).
x = torch.randn(10, 3)
y = torch.randn(10, 2)

In [10]:
print(x, x.shape)

tensor([[-2.7870,  1.7598,  0.1187],
        [ 0.6955, -0.7327, -0.1147],
        [-1.9928,  1.4445,  1.5361],
        [-0.5014, -0.5999,  0.8899],
        [ 1.0245,  0.2452, -0.2114],
        [ 0.6274, -0.0285,  0.9297],
        [ 0.0291, -0.5591, -1.9504],
        [ 2.8186, -0.4835, -0.2441],
        [-0.9032,  0.8295, -0.7762],
        [ 1.3787,  0.1821,  0.4072]]) torch.Size([10, 3])


In [11]:
# Build a fully connected layer.
linear = nn.Linear(3, 2)
print ('w: ', linear.weight)
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[-0.5200, -0.0766,  0.3555],
        [ 0.0157,  0.0779, -0.2214]], requires_grad=True)
b:  Parameter containing:
tensor([-0.2400,  0.0429], requires_grad=True)


In [12]:
# Build loss function and optimizer.
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

In [13]:
# Forward pass.
pred = linear(x)

In [14]:
# Compute loss.
loss = criterion(pred, y)
print('loss: ', loss.item())

loss:  1.760976791381836


In [15]:
# Backward pass.
loss.backward()

In [16]:
# Print out the gradients.
print ('dL/dw: ', linear.weight.grad) 
print ('dL/db: ', linear.bias.grad)

dL/dw:  tensor([[-1.2300, -0.1489,  0.2041],
        [-0.1537,  0.1380, -0.1021]])
dL/db:  tensor([-0.8278,  0.0200])


In [17]:
# 1-step gradient descent.
optimizer.step()

In [18]:
# You can also perform gradient descent at the low level.
# linear.weight.data.sub_(0.01 * linear.weight.grad.data)
# linear.bias.data.sub_(0.01 * linear.bias.grad.data)

# Print out the loss after 1-step gradient descent.
pred = linear(x)
loss = criterion(pred, y)
print('loss after 1 step optimization: ', loss.item())

loss after 1 step optimization:  1.7380443811416626


In [19]:
# ================================================================== #
#                     3. Loading data from numpy                     #
# ================================================================== #

# Create a numpy array.
x = np.array([[1, 2], [3, 4]])

# Convert the numpy array to a torch tensor.
y = torch.from_numpy(x)

# Convert the torch tensor to a numpy array.
z = y.numpy()

In [20]:
print(y, y.shape)

tensor([[1, 2],
        [3, 4]]) torch.Size([2, 2])


In [21]:
# ================================================================== #
#                         4. Input pipeline                           #
# ================================================================== #

# Download and construct CIFAR-10 dataset.
train_dataset = torchvision.datasets.CIFAR10(root='../../data/',
                                             train=True, 
                                             transform=transforms.ToTensor(),
                                             download=True)

  0%|          | 0/170498071 [00:00<?, ?it/s]

Extracting ../../data/cifar-10-python.tar.gz to ../../data/


In [22]:
print(train_dataset, len(train_dataset), type(train_dataset))

Dataset CIFAR10
    Number of datapoints: 50000
    Root location: ../../data/
    Split: Train
    StandardTransform
Transform: ToTensor() 50000 <class 'torchvision.datasets.cifar.CIFAR10'>


In [23]:
# Fetch one data pair (read data from disk).
image, label = train_dataset[0]
print (image.size())
print (label)

torch.Size([3, 32, 32])
6


In [24]:
# Data loader (this provides queues and threads in a very simple way).
train_loader = torch.utils.data.DataLoader(dataset=train_dataset,
                                           batch_size=64, 
                                           shuffle=True)

In [27]:
train_loader

In [25]:
# When iteration starts, queue and thread start to load data from files.
data_iter = iter(train_loader)

In [26]:
data_iter

In [32]:
# Actual usage of the data loader is as below.
cnt = 0
for images, labels in train_loader:
    # Training code should be written here.
    if cnt==0:
        print(images.shape, labels.shape, type(images), type(labels))
        print(labels)
    cnt=cnt+1
    pass

torch.Size([64, 3, 32, 32]) torch.Size([64]) <class 'torch.Tensor'> <class 'torch.Tensor'>
tensor([9, 1, 7, 8, 7, 1, 6, 8, 7, 2, 2, 8, 7, 8, 6, 5, 3, 4, 5, 4, 1, 8, 6, 8,
        7, 4, 4, 7, 8, 0, 0, 4, 2, 0, 3, 5, 6, 7, 8, 4, 9, 7, 2, 6, 6, 4, 7, 6,
        6, 0, 9, 8, 7, 7, 7, 7, 7, 4, 9, 3, 9, 8, 0, 9])


In [33]:
# ================================================================== #
#                5. Input pipeline for custom dataset                 #
# ================================================================== #

# You should build your custom dataset as below.
class CustomDataset(torch.utils.data.Dataset):
    def __init__(self):
        # TODO
        # 1. Initialize file paths or a list of file names. 
        pass
    def __getitem__(self, index):
        # TODO
        # 1. Read one data from file (e.g. using numpy.fromfile, PIL.Image.open).
        # 2. Preprocess the data (e.g. torchvision.Transform).
        # 3. Return a data pair (e.g. image and label).
        pass
    def __len__(self):
        # You should change 0 to the total size of your dataset.
        return 0 


In [35]:
# You can then use the prebuilt data loader. 
# custom_dataset = CustomDataset()
# train_loader = torch.utils.data.DataLoader(dataset=custom_dataset,
#                                            batch_size=64, 
#                                            shuffle=True)

In [36]:
# ================================================================== #
#                        6. Pretrained model                         #
# ================================================================== #

# Download and load the pretrained ResNet-18.
resnet = torchvision.models.resnet18(pretrained=True)

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth


  0%|          | 0.00/44.7M [00:00<?, ?B/s]

In [37]:
# If you want to finetune only the top layer of the model, set as below.
for param in resnet.parameters():
    param.requires_grad = False

In [38]:
resnet

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  

In [39]:
# Replace the top layer for finetuning.
resnet.fc = nn.Linear(resnet.fc.in_features, 100)  # 100 is an example.

In [40]:
resnet

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  

In [41]:
# Forward pass.
images = torch.randn(64, 3, 224, 224)
outputs = resnet(images)
print (outputs.size())     # (64, 100)

/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)


torch.Size([64, 100])


In [42]:
# ================================================================== #
#                      7. Save and load the model                    #
# ================================================================== #

# Save and load the entire model.
torch.save(resnet, 'model.ckpt')
model = torch.load('model.ckpt')

In [43]:
# Save and load only the model parameters (recommended).
torch.save(resnet.state_dict(), 'params.ckpt')
resnet.load_state_dict(torch.load('params.ckpt'))

<All keys matched successfully>